#!/usr/bin/env sh

DOCKER_VOLUME="/volume1/docker"
PROMETHEUS_ROOT="${DOCKER_VOLUME}/prometheus"

folders=( "configs" "data/alertmanager" "data/grafana" "data/prometheus" "data/snmp" )
for i in "${folders[@]}"; do
  [ ! -d ${PROMETHEUS_ROOT}/${i} ] && mkdir -p ${PROMETHEUS_ROOT}/${i} \
  && echo "folder created ${PROMETHEUS_ROOT}/${i}"
done

chown -R 65534:65534 ${PROMETHEUS_ROOT}/data/prometheus #nobody userid
chown -R 472:472 ${PROMETHEUS_ROOT}/data/grafana #grafana userid

configs=( "grafana.ini" "prometheus.yml" "telegraf.conf" )
for i in "${configs[@]}"; do
  curl -fsSL https://raw.githubusercontent.com/prahaladramji/synology-prometheus/master/configs/${i} -o ${PROMETHEUS_ROOT}/configs/${i}
  echo "config created ${PROMETHEUS_ROOT}/configs/${i}"
done
# get synology mibs
echo "Getting Synology MIBs.."
curl -fsSL https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/All/enu/Synology_MIB_File.zip -o ${PROMETHEUS_ROOT}/data/snmp
cd ${PROMETHEUS_ROOT}/data/snmp
echo "Extracting MIBs.."
7z e Synology_MIB_File.zip
rm -f Synology_MIB_File.zip


curl -fsSL https://raw.githubusercontent.com/prahaladramji/synology-prometheus/master/docker-compose.yml \
| sed "s/\${PROMETHEUS_ROOT}/${PROMETHEUS_ROOT//\//\\/}/g" > ${PROMETHEUS_ROOT}/docker-compose.yml
echo "docker-compose file created ${PROMETHEUS_ROOT}/docker-compose.yml"

docker-compose -f ${PROMETHEUS_ROOT}/docker-compose.yml up -d

echo "
#############################################
Grafana       http://`hostname`:3000
Prometheus    http://`hostname`:9090
Alertmanager  http://`hostname`:9093
Node-Exporter http://`hostname`:9100/metrics
"
